output_dir: ./experiment/

dataset:
  class: Drugbank
  path: ./data/
  split: random
  threshold: 30

task:
  class: classification
  model:
    class: HGC
  train: kfold

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  device: [1]
  batch_size: 512

train:
  num_epoch: 1000

eval_metric: ['roc-auc', 'pr-auc', 'range_logAUC', 'accuracy', 'precision', 'recall', 'f1']
score_metric: f1